# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20170520_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='anger',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
