# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_anger_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='anger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anger_level', to='apps.Anger'),
        ),
    ]
