# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20170529_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture_feeling',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
