# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_post_picture_feeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_feeling',
            field=models.ImageField(null=True, upload_to='static/image/%Y/%m/%d'),
        ),
    ]
