# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20170611_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(db_column='title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_feeling',
            field=models.ImageField(null=True, upload_to='image/%Y/%m/%d'),
        ),
    ]
